In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [252]:
s1=pd.read_csv('Meditation experiment with tagging-1/NFB_17-4-2019_20-48._FP2csv.csv',names=['X','Y'])
s2=pd.read_csv('Meditation experiment with tagging-1/NFB_17-4-2019_22-35_F4.csv',names=['X','Y'])
s3=pd.read_csv('Meditation experiment with tagging-1/NFB_18-4-2019_0-13_O2.csv',names=['X','Y'])
s4=pd.read_csv('Meditation experiment with tagging-1/NFB_18-4-2019_21-17._P4. csv.csv',names=['X','Y'])
s1=s3[12:]
s2=s2[3:]
s3=s3[12:]
s4=s4[3:]
#s3.X=s3.X.astype(float)

In [253]:
s=s1.append(s2.append(s3.append(s4)))
print(s)
s.X=s.X.astype(float)

                X  Y
12      -35768.88  0
13      -35776.61  0
14      -35743.90  0
15      -35672.68  0
16      -35584.84  0
17      -35521.47  0
18      -35530.38  0
19      -35639.73  0
20      -35833.74  0
21      -36052.32  0
22      -36216.17  0
23      -36269.10  0
24      -36211.43  0
25      -36094.01  0
26      -35985.30  0
27      -35940.94  0
28      -35975.62  0
29      -36058.86  0
30      -36121.15  0
31      -36087.05  0
32      -35920.49  0
33      -35655.69  0
34      -35390.91  0
35      -35243.60  0
36      -35287.48  0
37      -35520.36  0
38      -35865.79  0
39      -36201.35  0
40      -36406.73  0
41      -36402.24  0
...           ... ..
456937   -24458.1  0
456938   -24347.2  0
456939   -24234.7  0
456940   -24129.6  0
456941   -24030.3  0
456942   -23938.6  0
456943   -23868.5  0
456944   -23838.4  0
456945   -23854.5  0
456946   -23904.1  0
456947   -23969.7  0
456948   -24041.9  0
456949   -24119.9  0
456950   -24198.7  0
456951   -24267.8  0
456952   -243

In [50]:
for i in range(12,453860):
    if(s3.Y[i]==39):
        for _ in range(i-1250,i-16250,-1):
            if s3.Y[_]!=0:
                i+=1500
                break
            else:
                s3.Y[i-16250:i-1250]=1

C:\Users\Turiya\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [51]:
temp=s3
#rows=temp.shape[0]
temp=temp[temp['Y']!=0]
temp=temp[temp['Y']!=39]
print(temp.tail(5))
print(temp.shape)

               X   Y
445992 -35769.84  38
445993 -35602.02  38
445994 -35494.02  38
445995 -35484.65  38
445996 -35566.33  38
(147054, 2)


In [52]:
X=temp['X']
X=X.values.reshape(-1,1)
Y=temp['Y']

# grouping of data

In [208]:
gtemp=temp.groupby('Y')
y=[]

In [209]:
g1=gtemp.get_group(1)
g32=gtemp.get_group(32)
g37=gtemp.get_group(37)
g38=gtemp.get_group(38)

In [210]:
n_features=1
totaldp=0
window=300
X=g1['X']
data_points=X.shape[0]//window
y=np.append(y,[1]*data_points)
totaldp+=data_points
X=X.head(data_points*window)
X=np.array(X)
X=np.reshape(X,((data_points,window,n_features)))
groupedX=X
X=g32['X']
data_points=X.shape[0]//window
y=np.append(y,[32]*data_points)
totaldp+=data_points
X=X.head(data_points*window)
X=np.array(X)
X=np.reshape(X,((data_points,window,n_features)))
groupedX=np.append(groupedX,X)
X=g37['X']
data_points=X.shape[0]//window
y=np.append(y,[37]*data_points)
totaldp+=data_points
X=X.head(data_points*window)
X=np.array(X)
X=np.reshape(X,((data_points,window,n_features)))
groupedX=np.append(groupedX,X)
X=g38['X']
data_points=X.shape[0]//window
y=np.append(y,[38]*data_points)
totaldp+=data_points
X=X.head(data_points*window)
X=np.array(X)
X=np.reshape(X,((data_points,window,n_features)))
groupedX=np.append(groupedX,X)
groupedX=np.reshape(groupedX,((totaldp,window,n_features)))

# extracting features

In [217]:
X=groupedX
a=np.max(X,axis=1)
    #print(a.shape)
    #b=np.min(X,axis=1)
a=np.concatenate((a,np.min(X,axis=1)),axis=1)
a=np.concatenate((a,np.average(X,axis=1)),axis=1)
a=np.concatenate((a,np.std(X,axis=1)),axis=1)
a=np.real(np.fft.rfftn(X,axes=(0,1)))[:,0]

# algos

In [244]:
X=X.reshape(-1,window)
print(y_test.shape)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

(162,)


In [245]:
from sklearn.svm import SVC
clf = SVC(kernel='linear') 
clf.fit(X_train,y_train)
clf.score(X_test,y_test)
y_pre=clf.predict(X_test)

In [246]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

In [247]:
actual=y_test
predicted=y_pre
results = confusion_matrix(actual, predicted) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(actual, predicted) )
#print ('Report : ')
print (classification_report(actual, predicted) )

Confusion Matrix :
[[32  0 19  3]
 [ 0  0  1  0]
 [20  0 27 19]
 [ 1  0 14 26]]
Accuracy Score : 0.5246913580246914
              precision    recall  f1-score   support

         1.0       0.60      0.59      0.60        54
        32.0       0.00      0.00      0.00         1
        37.0       0.44      0.41      0.43        66
        38.0       0.54      0.63      0.58        41

   micro avg       0.52      0.52      0.52       162
   macro avg       0.40      0.41      0.40       162
weighted avg       0.52      0.52      0.52       162



C:\Users\Turiya\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
