In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
temp=pd.read_csv('trimmedData.csv')

In [3]:
X=temp['X']
X=X.values.reshape(-1,1)
Y=temp['Y']

# grouping of data

In [4]:
gtemp=temp.groupby('Y')
y=[]

In [5]:
g1=gtemp.get_group(1)
g2=gtemp.get_group(2)
g32=gtemp.get_group(32)
g37=gtemp.get_group(37)
g38=gtemp.get_group(38)

In [6]:
n_features=1
totaldp=0
window=100
X=g1['X']
data_points=X.shape[0]//window
y=np.append(y,[1]*data_points)
totaldp+=data_points
X=X.head(data_points*window)
X=np.array(X)
X=np.reshape(X,((data_points,window,n_features)))
groupedX=X
X=g2['X']
data_points=X.shape[0]//window
y=np.append(y,[2]*data_points)
totaldp+=data_points
X=X.head(data_points*window)
X=np.array(X)
X=np.reshape(X,((data_points,window,n_features)))
groupedX=np.append(groupedX,X)
X=g32['X']
data_points=X.shape[0]//window
y=np.append(y,[32]*data_points)
totaldp+=data_points
X=X.head(data_points*window)
X=np.array(X)
X=np.reshape(X,((data_points,window,n_features)))
groupedX=np.append(groupedX,X)
X=g37['X']
data_points=X.shape[0]//window
y=np.append(y,[37]*data_points)
totaldp+=data_points
X=X.head(data_points*window)
X=np.array(X)
X=np.reshape(X,((data_points,window,n_features)))
groupedX=np.append(groupedX,X)
X=g38['X']
data_points=X.shape[0]//window
y=np.append(y,[38]*data_points)
totaldp+=data_points
X=X.head(data_points*window)
X=np.array(X)
X=np.reshape(X,((data_points,window,n_features)))
groupedX=np.append(groupedX,X)
groupedX=np.reshape(groupedX,((totaldp,window,n_features)))

# extracting features

In [7]:
X=groupedX
a=np.max(X,axis=1)
    #print(a.shape)
    #b=np.min(X,axis=1)
a=np.concatenate((a,np.min(X,axis=1)),axis=1)
a=np.concatenate((a,np.average(X,axis=1)),axis=1)
a=np.concatenate((a,np.std(X,axis=1)),axis=1)
a=np.real(np.fft.rfftn(X,axes=(0,1)))[:,0]

# algos

In [58]:
X=X.reshape(-1,window)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
print(y_test.shape)

(2170,)


# SVM

In [10]:
from sklearn.svm import SVC
clf = SVC(kernel='linear') 
clf.fit(X_train,y_train)
clf.score(X_test,y_test)
y_pre=clf.predict(X_test)

In [11]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

In [12]:
actual=y_test
predicted=y_pre
results = confusion_matrix(actual, predicted) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(actual, predicted) )
#print ('Report : ')
print (classification_report(actual, predicted) )

Confusion Matrix :
[[807   7   0 218   9]
 [229   4   0   0   0]
 [  3   0   0   2   0]
 [320   3   3 282  19]
 [ 82   0   7 161  14]]
Accuracy Score : 0.5101382488479262
              precision    recall  f1-score   support

         1.0       0.56      0.78      0.65      1041
         2.0       0.29      0.02      0.03       233
        32.0       0.00      0.00      0.00         5
        37.0       0.43      0.45      0.44       627
        38.0       0.33      0.05      0.09       264

   micro avg       0.51      0.51      0.51      2170
   macro avg       0.32      0.26      0.24      2170
weighted avg       0.46      0.51      0.45      2170



# Decision Tree

In [48]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier().fit(X_train, y_train)
clf.score(X_test,y_test)
y_pre=clf.predict(X_test)

In [33]:
actual=y_test
predicted=y_pre
results = confusion_matrix(actual, predicted) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(actual, predicted) )
#print ('Report : ')
print (classification_report(actual, predicted) )

Confusion Matrix :
[[848  85   0  90   2]
 [ 75 110   0  24   0]
 [  0   0   1   1   9]
 [161  27   0 405  73]
 [ 21   0   4  67 167]]
Accuracy Score : 0.7055299539170506
              precision    recall  f1-score   support

         1.0       0.77      0.83      0.80      1025
         2.0       0.50      0.53      0.51       209
        32.0       0.20      0.09      0.13        11
        37.0       0.69      0.61      0.65       666
        38.0       0.67      0.64      0.65       259

   micro avg       0.71      0.71      0.71      2170
   macro avg       0.56      0.54      0.55      2170
weighted avg       0.70      0.71      0.70      2170



# Random Forest

In [61]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=100)
clf.fit(X_train,y_train)
clf.score(X_test,y_test)
y_pred=clf.predict(X_test)

In [62]:
actual=y_test
predicted=y_pred
results = confusion_matrix(actual, predicted) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(actual, predicted) )
#print ('Report : ')
print (classification_report(actual, predicted) )

Confusion Matrix :
[[952  33   0  65   0]
 [113 108   0   0   0]
 [  0   0   0   0   6]
 [ 71  18   0 503  41]
 [  5   0   0  37 218]]
Accuracy Score : 0.8207373271889401
              precision    recall  f1-score   support

         1.0       0.83      0.91      0.87      1050
         2.0       0.68      0.49      0.57       221
        32.0       0.00      0.00      0.00         6
        37.0       0.83      0.79      0.81       633
        38.0       0.82      0.84      0.83       260

   micro avg       0.82      0.82      0.82      2170
   macro avg       0.63      0.61      0.62      2170
weighted avg       0.81      0.82      0.81      2170



C:\Users\Turiya\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
