In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
temp=pd.read_csv('trimmedData.csv')
X=temp['X']
X=X.values.reshape(-1,1)
Y=temp['Y']

In [3]:
gtemp=temp.groupby('Y')
y=[]
g1=gtemp.get_group(1) 
g2=gtemp.get_group(2)
g32=gtemp.get_group(32)
g37=gtemp.get_group(37)
g38=gtemp.get_group(38)

In [4]:
n_features=1
totaldp=0
window=250

X=g1['X']
data_points=X.shape[0]//window
y=np.append(y,[1]*data_points)
totaldp+=data_points
X=X.head(data_points*window)
X=np.array(X)
X=np.reshape(X,((data_points,window,n_features)))
groupedX=X
X=g2['X']
data_points=X.shape[0]//window
y=np.append(y,[2]*data_points)
totaldp+=data_points
X=X.head(data_points*window)
X=np.array(X)
X=np.reshape(X,((data_points,window,n_features)))
groupedX=np.append(groupedX,X)
X=g32['X']
data_points=X.shape[0]//window
y=np.append(y,[32]*data_points)
totaldp+=data_points
X=X.head(data_points*window)
X=np.array(X)
X=np.reshape(X,((data_points,window,n_features)))
groupedX=np.append(groupedX,X)
X=g37['X']
data_points=X.shape[0]//window
y=np.append(y,[37]*data_points)
totaldp+=data_points
X=X.head(data_points*window)
X=np.array(X)
X=np.reshape(X,((data_points,window,n_features)))
groupedX=np.append(groupedX,X)
X=g38['X']
data_points=X.shape[0]//window
y=np.append(y,[38]*data_points)
totaldp+=data_points
X=X.head(data_points*window)
X=np.array(X)
X=np.reshape(X,((data_points,window,n_features)))
groupedX=np.append(groupedX,X)
groupedX=np.reshape(groupedX,((totaldp,window,n_features)))

In [5]:
'''for i in range(groupedX.shape[0]):
    groupedX[i]=groupedX[i]-np.mean(groupedX[i])'''

'for i in range(groupedX.shape[0]):\n    groupedX[i]=groupedX[i]-np.mean(groupedX[i])'

In [6]:
artifactInd=pd.read_csv('artifact predicted svm xtreme.csv',names=['a'])

In [7]:
lst=artifactInd.a.values.tolist()
lst=[int(i) for i in lst]
print(groupedX.shape)
groupedX=np.delete(groupedX,lst,axis=0)
groupedX.shape

(2628, 250, 1)


(2615, 250, 1)

In [8]:
y=np.delete(y,lst,axis=0)
y.shape

(2615,)

In [19]:
X=groupedX
a=np.max(X,axis=1)
    #print(a.shape)
    #b=np.min(X,axis=1)
a=np.concatenate((a,np.min(X,axis=1)),axis=1)
a=np.concatenate((a,np.average(X,axis=1)),axis=1)
a=np.concatenate((a,np.std(X,axis=1)),axis=1)
a=np.concatenate((a,np.real(np.fft.rfftn(X,axes=(0,1),norm='ortho'))[:,0]),axis=1)
X=a

In [20]:
#print(X)
from sklearn.preprocessing import MinMaxScaler 
scaler = MinMaxScaler(feature_range=(0, 1)) 
rescaledX = scaler.fit_transform(X) 
#print(rescaledX)
X=rescaledX

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
print(y_test.shape)

(863,)


In [28]:
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report

In [29]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier().fit(X_train, y_train)
clf.score(X_test,y_test)
y_pre=clf.predict(X_test)

In [30]:
actual=y_test
predicted=y_pre
results = confusion_matrix(actual, predicted) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(actual, predicted) )
#print ('Report : ')
print (classification_report(actual, predicted) )

Confusion Matrix :
[[384  17   0  20   1]
 [ 22  54   0  15   0]
 [  0   0   1   0   0]
 [ 22  10   0 223  11]
 [  3   0   1  13  66]]
Accuracy Score : 0.8435689455388181
              precision    recall  f1-score   support

         1.0       0.89      0.91      0.90       422
         2.0       0.67      0.59      0.63        91
        32.0       0.50      1.00      0.67         1
        37.0       0.82      0.84      0.83       266
        38.0       0.85      0.80      0.82        83

   micro avg       0.84      0.84      0.84       863
   macro avg       0.75      0.83      0.77       863
weighted avg       0.84      0.84      0.84       863



In [31]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(n_estimators=50)
clf.fit(X_train,y_train)
clf.score(X_test,y_test)
y_pre=clf.predict(X_test)

In [32]:
actual=y_test
predicted=y_pre
results = confusion_matrix(actual, predicted) 
print ('Confusion Matrix :')
print(results) 
print ('Accuracy Score :',accuracy_score(actual, predicted) )
#print ('Report : ')
print (classification_report(actual, predicted) )

Confusion Matrix :
[[382  17   0  20   3]
 [ 24  63   0   4   0]
 [  0   0   0   0   1]
 [ 20  10   0 235   1]
 [  2   0   0   8  73]]
Accuracy Score : 0.8725376593279258
              precision    recall  f1-score   support

         1.0       0.89      0.91      0.90       422
         2.0       0.70      0.69      0.70        91
        32.0       0.00      0.00      0.00         1
        37.0       0.88      0.88      0.88       266
        38.0       0.94      0.88      0.91        83

   micro avg       0.87      0.87      0.87       863
   macro avg       0.68      0.67      0.68       863
weighted avg       0.87      0.87      0.87       863



C:\Users\Babbar\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


1. We cannot use mean subtraction from each chunk separately to classify
between the mind stages, it reduces accuracy - Amplitude has a key role
in predictions
2. Preprocessing using standard scaler also had a bad impact on the
prediction
